### ISSUE TITLE
Reorganize the Flocking file system layout to be simpler and more idiomatic

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/Flocking#101]
Currently, Flocking's layout on the file system is a little bit more complex than it needs to be. Here's a preferable structure:

    flocking/
        src/
            <all of flocking's non-ugen source files>
            ugens/
                <all ugen files>
        flocking/
            <all of flocking's built files>.js
        nodejs/
        demos/
            playground/
            moogy/
            <other demos>
        tests/
        docs/

Other renaming/restructuring improvements:
 * All demos should have a top-level <code>index.html</code> so they can be easily viewed
 * the prefix <code>flocking-</code> should be removed from as many files as possible, including the core files
 * jQuery and other dependencies should be sourced via npm
 * A flocking-core.js build file should be created that includes all of the non-view parts of Flocking along with Infusion's jQuery-standalone.js file instead of a full version of jQuery (which is the largest dependency included in flocking-all.js)
 * Break out unit generators into smaller module files (oscillators, envelopes, triggers, etc.)

**Comment by drart** [comment]
I would also add a doc folder in the top level. I would suggest moving tests into src for clarity and perhaps moving the playground into the demo folder. Also, if it is going to be more canonical then the flocking folder should probably be called build.

**Comment by colinbdclark** [comment]
Thanks, I added the docs directory. It will stay in the same location it's in.

The reason for renaming the directory-that-is-currently-called-<code>dist</code> to <code>flocking</code> is for ease of use. Users can download a Flocking release, grab the <code>flocking</code> directory, and drop it into their application. [Whereas currently](https://github.com/colinbdclark/Flocking/blob/master/docs/getting-started.md), we tell them to take the <code>dist</code> directory and rename it. While it seems strange to have a <code>flocking</code> directory inside Flocking, it seemed the best way to make it painless to get up and running with.

I had a look at a few other frameworks (jQuery, Angular, Ember, and Infusion), and they all keep their unit tests in a top-level <code>tests</code> or <code>test</code> folder.

I had been thinking that the Playground was a prominent enough part of Flocking that I should pull it out to top-level, but I think your'e right, @drart, that it works fine in the <code>demos</code> folder.

**Comment by colinbdclark** [comment]
Substantial changes for this issue have been occurring recently in the infusion-2.x branch and tracked under issue #111. It's coming along.
