### ISSUE TITLE
flock.ugen.mouse.click events

### ISSUE THREAD

**Issue by davidpaulrosser** [colinbdclark/Flocking#121]
Hey,

Is there anyway to subscribe to events that listen for when the sound is played / changed?

For instance when using the ugen 'flock.ugen.mouse.click' I'd like to know when the mouse is down / released and have a model of the data thats changed when the mouse is down.

Any help greatly appreciated.

Thanks,

David.

**Comment by colinbdclark** [comment]
Yep, you can use <code>flock.ugen.triggerCallback</code> to invoke a function when a trigger fires (i.e. its signal passes from <=0 to >0). The <code>triggerCallback</code> unit generator just passes through its <code>source</code> input, so you can just insert it in line with a trigger such as <code>flock.ugen.mouse.click</code>.

There's a basic example in the Flocking Playground:

http://flockingjs.org/demos/interactive/html/playground.html#triggerCallback
