### ISSUE TITLE
How do you trigger a synth?

### ISSUE THREAD

**Issue by SelStefan** [colinbdclark/Flocking#127]
How do you "bang" or trigger a synth programmatically, also I'm guessing that you would have to untrigger a synth later since it shouldn't stay up on the sustain value forever. So how can you trigger/untrigger a synth or emulate such behaviour?

**Comment by colinbdclark** [comment]
In Flocking 0.1, synths themselves have no notion of triggers or bangs. Their underlying unit generators, however, may have either a) trigger inputs that can be activated whenever a signal cross the zero line or b) gate inputs that will open and close when they receive positive and negative values. This is similar in concept to other unit generator-based systems such as SuperCollider.

In your case, you're probably wondering how to open and close an envelope generator such as an ADSR envelope, which is modulating the amplitude of your synth? The key is the gate input.

There are a variety unit generators you can use as signal inputs to an envelope's gate (e.g. a pulse wave, or the mouse click ugen, etc.). Or you can just manually open and close the gate with calls to <code>set()<code>:

    var s = flock.synth({
        synthDef: {
            ugen: "flock.ugen.sin",
            mul: {
                id: "env",
                ugen: "flock.ugen.asr",
                gate: 0
            }
        }
    });

    // Open the gate, causing the envelope generator to start its attack phase.
    s.set("env.gate", 1);

    // Later, close the gate, causing it to transition to the release phase.
    s.set("env.gate", 0);

The various envelope demos in the Playground show different types of triggers and gates in practice:
http://flockingjs.org/demos/interactive/html/playground.html#asr

Documentation on triggers is available here:
https://github.com/colinbdclark/Flocking/blob/master/docs/ugens/triggers.md

A discussion about envelopes, along with some proto-documentation is available here:
https://github.com/colinbdclark/Flocking/issues/8#issuecomment-108712105

Flocking 0.2.0 will make this process slightly smoother by introducing noteOn() and noteOff() events. It will also have a new sequencer unit generator, which can be used to schedule signal changes over time:
http://flockingjs.org/next/demos/playground/#sequencer

I hope this helps!

**Comment by SelStefan** [comment]
Yup, this is exactly what I need. Thank you for the quick reply. :)

**Comment by bennlich** [comment]
@colinbdclark This answer is pretty awesome actually. Maybe parts should be moved to the trigger docs? And the #8 comment could be the beginning of an envelopes doc? Let me know if you want me to take a stab at that.

**Comment by colinbdclark** [comment]
I would love for you to take a stab at some new documentation, @bennlich. That's wonderful! I tried to structure these comments in (and the ones in #8) in such a way that they should be relatively easy to migrate and flesh out. If you feel like you've got some time to look into it, I'm happy to help answer questions or review pull requests. Thanks so much!

**Comment by bennlich** [comment]
Cool! I'd be happy to try some things. Do you think it would make sense to add a new `gates.md`? Or better to stick the gate info into `triggers.md`?

Do you have a master plan for what you want the documentation to look like eventually?

**Comment by colinbdclark** [comment]
I think either is fine. What's your preference?

I don't have a specific vision for how the documentation will look in the long run, except that it's often useful to break up tutorials and "here's how you do actual stuff" from reference documentation that thoroughly lists the API, inputs, etc. for each component in the system.

I can imagine that, given the relative dearth of documentation today, the former is probably the most immediately valuable documentation, especially if it's broken down into fairly familiar themes such as "Making a synth," "Triggering notes," "Sequencing patterns" and that sort of thing.

I'm interested in suggestions on how best to structure this, too, though.

**Comment by bennlich** [comment]
Nice! I'll do some thinking about this.

Do you have any thoughts about including documentation within the code itself? For example, I was imagining that the list of envelope curves at the bottom of #8 could live somewhere around [here](https://github.com/colinbdclark/Flocking/blob/c7b4ce76adeea35e29cef463954b3500f584ce14/src/ugens/envelopes.js#L338-L340).

**Comment by colinbdclark** [comment]
I think it's a good idea, especially if we settle on a documentation generation tool eventually. I have used a kind of pseudo-jsdoc convention in many places in the code, but never looked into what the latest tools are for generating documentation from source code. In the meantime, I've tried to at least put code comments in for many unit generators, knowing how bad the rest of Flocking's documentation is. As you say, all of the line generators are lacking such inline documentation.

Longer term, I've also imagined more structured, declarative form of metadata about inputs for each unit generator (sorted in each unit generators <code>ugenDefaults</code> so that a user of the Playground could see a list of inputs support, with value ranges and a short description, etc. This would be great for autocomplete and other kinds of graphical programming supports too.

But one step at a time. :)

**Comment by bennlich** [comment]
> Do you think it would make sense to add a new gates.md? Or better to stick the gate info into triggers.md?

>> I think either is fine. What's your preference?

I'll think about this too. Probably doesn't matter much, but if they're separate maybe they should link to each other.

Some general, late-at-night documentation thoughts:
I think one of the most important things for documentation to succeed at is "findability." I think Leaflet is good at this in certain ways (see [here](http://leafletjs.com/reference.html), though the reference was recently updated, and I haven't used this latest version much).

I've always found the table-y bit at the top to be super useful, since it provides an overview of everything you can ever do, and it's not all that many things. I also like that you can command-f through the entire reference at once since it's all on one page. But Leaflet is also blessed (by design, I suppose) with a pretty freaking small API.

And then they combine this with a few tutorials (though not many), the most important being the [quick start](http://leafletjs.com/examples/quick-start.html), which you already got going for Flocking.

> But one step at a time. :)

For sure! Looks like you've put a ton of work into this...

**Comment by bennlich** [comment]
> so that a user of the Playground could see a list of inputs support, with value ranges and a short description, etc.

Yeah that would be pretty awesome :-)

**Comment by bennlich** [comment]
Actually, I think I'm fuzzy on the difference between a gate and a trigger.

Is a trigger a type of input that calls an arbitrary callback whenever its input value changes sign?

And then is a gate just a special type of trigger with a "change the amplitude of my own output" callback? I guess this interpretation doesn't really hold for envelope ugens, which have changing stages--do they interpret gates in a special way?

**Comment by colinbdclark** [comment]
Good question. The difference between a trigger and a gate has less to do with the type of signal than how it is interpreted by the receiver. 

A trigger is a type of signal that causes a change to happen in another unit generator whenever its value crosses from non-positive to positive. The trigger is not fired again until the signal's value goes to 0 or less, and then crosses back into the positive. <code>flock.ugen.impulse</code> and <code>flock.ugen.dust</code> are often used as triggers; they output a short one-sample burst of a positive value periodically, which can be used to trigger some behaviour in another unit generator. So for example, <code>flock.ugen.triggerGrains</code> will emit a new grain each time it receives a trigger signal. Similarly, <code>flock.ugen.latch</code> will hold onto its value until it receives a trigger, at which point it will pick up a new value. <code>flock.ugen.playBuffer</code> will reset its playback state to the beginning whenever it receives a trigger.

A gate, on the other hand, stays open for a period of time. A gate opens whenever the signal's value goes above 0, and causes some action to occur in another unit generator for the duration that it stays in the range above 0. The gate closes whenever the signal drops to 0 or less. Envelopes are the classic example of a unit generator that employs a gate; the envelope, if it has a <code>sustainPoint</code> defined, will stay open at its sustain point for as long as its gate signal is open.

[Cottle's SuperCollider tutorial](http://www.mat.ucsb.edu/275/CottleSC3.pdf) discusses triggers and gates a bit (on page 101), and may be helpful.

Does this make help?

**Comment by bennlich** [comment]
Yes, this clears it up, thanks.

And Cottle's tutorial was great. I found this especially concise:

> A gate is a trigger and duration. (A trigger is a gate with 0 duration.)

And then:

> Triggers are used for fixed length envelopes. A gate can be used for both fixed and sustaining envelopes, but it is necessary for sustained envelopes. The duration of the gate defines sustain time.

**Comment by colinbdclark** [comment]
You're right, the Leaflet documentation is really fantastic! Lookin at their Quick Start, I wonder if eventually we need to also improve the Flocking quick start tutorial to capture a few more of the common things people want to do with. For example, perhaps showing how to build a [synth like this one](https://github.com/colinbdclark/flocking-examples/tree/master/ui-controls) or how to do basic sonification?

**Comment by bennlich** [comment]
In my mind, the purpose of a quick start tutorial is to get people working with the library as fast as possible. Maybe some steps of incremental complexity could be:

- create a synth with only 1 ugen
- create a synth with 1 ugen modulated by another
- interact with a synth from outside of flocking (i.e. from a non-ugen; basic sonification might be one way to address this)
- could maybe address the role of the band synth?

(Btw, I love how the playground lets you work with JSON descriptions alone without having to touch anything else.)

I was a little surprised that the flocking [getting started guide](https://github.com/colinbdclark/Flocking/blob/master/docs/getting-started.md) spends time with Infusion, strict mode, etc. Maybe some of that could be split off into "best practices for architecting a flocking synth", or something along those lines? I haven't dug into Fluid at all yet though, so part of this might just be me not understanding its role.

The synth you linked to is awesome! Why isn't that hosted somewhere on the homepage? :-D But it also seems kinda complex to me for a quick-start guide. Maybe it should have its own tutorial?

> I also like the 1) description-usage 2) example 3) options table structure of Leaflet's reference documentation a lot. It could work really well for each Flocking unit generator.

Yeah. And I can totally imagine a list like this for each ugen:

![screen shot 2015-12-10 at 2 22 02 pm](https://cloud.githubusercontent.com/assets/704368/11728882/7ebea0ca-9f49-11e5-9e63-5bca9b8f7279.png)

> I think with the 0.2.0 release we could even embed a tiny inline version of the Flocking Playground in the documentation so that each example is tweakable and playable by the user.

Yesssssss. Another possible inspiration: http://paperjs.org/reference/gradient/

**Comment by bennlich** [comment]
Interestingly, it looks like the leaflet docs aren't generated automatically--they're just kept up-to-date by hand. For example, see [these commits](https://github.com/Leaflet/Leaflet/commits/gh-pages-master/reference.html). On the gh-pages branch, there a [template file](https://github.com/Leaflet/Leaflet/blob/gh-pages-master/reference-tpl.html) that tells you what HTML layout to use to document different types of objects, and then there's [a single reference file](https://github.com/Leaflet/Leaflet/blob/gh-pages-master/reference.html) with all the reference HTML in it. Kind of surprising.
