### ISSUE TITLE
fading

### ISSUE THREAD

**Issue by Phalanstere** [colinbdclark/Flocking#130]
I have scanned the documentation to find out how I may trigger a fadeIn opr fadeOut command for a synthesizer, but to no avail. Elucidation would be great.

**Comment by colinbdclark** [comment]
Hi @Phalanstere, the documentation definitely needs to be improved in this regard (contributions are hugely welcome). In the meantime, have a look at the conversation on #127, and at the various envelope-related playground demos.

**Comment by Phalanstere** [comment]
Thanks, Colin, that was helpful. – Found out, that using attack parameter was helpful - as any working sample. The playground is great, I've seen that before and it actually convinced of using flocking.js.
Is there a site where the community of your user uploads sound effects?

**Comment by colinbdclark** [comment]
The long-term idea I have been thinking through is to turn the Playground a much more useful environment for experimenting with and prototyping Flocking applications. It will support Github's Gists as a persistence and versioning mechanism. This will make it much easier to see, share, fork, and modify synths made by other people in the Flocking community. I really want to avoid the case where there's one centralized Flocking-specific database, and instead to integrate with the tools (such as Github) where developers already work. We'll use PouchDB or an equivalent to also help with caching and offline support.

Right now, that's slated for the Flocking 1.1.0 release, but I'm always happy to shuffle around the release priorities based on what people in the community are most interested in and able to contribute to.

https://github.com/colinbdclark/Flocking/wiki/Release-Plan#110-collaborative-playground

In the meantime, if you've got a cool demo or example, I'm always happy to take pull requests to add them to the Playground. The Playground code itself has undergone a huge amount of change between the 0.1.x line and the upcoming 0.2.0 release (which is currently being developed in the master branch), so I may need to coach you through how to contribute, but it's pretty straightforward.

Thoughts, suggestions, and pull requests for the Playground are, as always, hugely welcome.
