### ISSUE TITLE
The example in the "Schedulers" section in the README.md doesn't work

### ISSUE THREAD

**Issue by anthoq88** [colinbdclark/Flocking#134]
Hello,

I get these errors when I copy and paste the config from the README.md under the "Schedulers" section.

![screen shot 2015-11-11 at 9 07 25 pm](https://cloud.githubusercontent.com/assets/1674432/11088715/6f30e318-88b8-11e5-8b58-970f829cd8d5.png)

**Comment by colinbdclark** [comment]
Good catch, thanks @anthoq88! The example had some how been corrupted and was not correctly structured. I've fixed the documentation in master.

You can also try the "Declarative Scheduling" demo in the playground, which is the same example.
