### ISSUE TITLE
Trigger buffer playback playground example gives a 404

### ISSUE THREAD

**Issue by bennlich** [colinbdclark/Flocking#142]
http://flockingjs.org/next/demos/playground/#playbuffer-trigger

`GET http://flockingjs.org/next/demos/playground/demos/playbuffer-trigger.js 404 (Not Found)`

**Comment by colinbdclark** [comment]
The case of the demo name was incorrect (uppercase B in "playBuffer"), which given the way demo names are mapped to file names worked on the Mac (with its case-insensitive filesystem), but failed on Linux. The correct URL for that demo is now:

http://flockingjs.org/next/demos/playground/#playBuffer-trigger

Thanks for catching this, @bennlich!
