### ISSUE TITLE
Add explicit events for MIDI clock messages

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/Flocking#168]
Currently, MIDI clock messages are supported only at a low level, exposed as raw system messages. We should add higher-level semantic events for MIDI start, continue, stop, and clock events.

**Comment by colinbdclark** [comment]
The low-level infrastructure for parsing MIDI clock events has been added, but I wonder if we should expose these as events on the <code>flock.midi.receiver</code> base grade? @the-t-in-rtf, what do you think?

**Comment by the-t-in-rtf** [comment]
As we discussed via chat, it seems like something pretty useful that we'll eventually need.
