### ISSUE TITLE
No sound on Firefox 45.0.1, ArchLinux

### ISSUE THREAD

**Issue by hamoid** [colinbdclark/Flocking#170]
Firefox: Flocking=no sound, Gibberish=no sound
but
Chromium: Flocking=works, Gibberish=works

Is there some flag that needs to be toggled for having audio synthesis in Linux Firefox?

**Comment by colinbdclark** [comment]
Hi @hamoid,

Sorry to hear you're not getting any sound output on your copy of Firefox. I'm not a Linux expert at all, but could it be an ALSA or pulseaudio configuration issue on your computer? I just installed a fresh copy of Fedora 23 in a virtual machine, and I'm hearing sound on all the Flocking examples in Firefox 45.0.1. I had a colleague try on his Thinkpad running OpenSUSE Tumbleweed in Firefox 45.0.1, and it also worked there.

**Comment by hamoid** [comment]
Hi @colinbdclark,

Thanks! The funny thing is, I do get sound in YouTube or Vimeo for instance. It's just audio synthesis using the webaudio api that silently fails. I was asking here in case someone knows, but I guess it makes sense to close this issue and open it maybe on Firefox... I asked here in case it was a known issue.

**Comment by hamoid** [comment]
Ok this is embarrasing... I started Firefox in safe mode (without any plugins) and it worked! But then I started again with my plugins enabled, and it still works! 

Maybe something got fixed when starting in safe mode. Restarting the computer or Firefox was not enough, but the safe mode did it.

**Comment by colinbdclark** [comment]
Glad to hear you got it working, and no problem at all. I was glad to have the opportunity to test again in Linux.
