### ISSUE TITLE
Flocking's MIDI implementation on Node.js creates MIDI ports overly-eagerly, causing issues with ALSA on Linux

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/Flocking#197]
The implementation of Flocking's MIDI support in Node.js is excessively eager about creating node-midi <code>MIDIIn</code> and <code>MIDIOut</code> objects. In particular, a node-midi <code>midi.input</code> or <code>midi.output</code> [instance is created](https://github.com/colinbdclark/Flocking/blob/midi-improvements/src/nodejs/midi.js#L62) whenever a <code>MIDIPort</code> object is instantiated. 

The issue here is that <code>MIDIPort</code>s are created anew each time a user enumerates the list of MIDI ports connected to a <code>flock.midi.system</code> using the <code>refreshPorts()</code> invoker. However, @simonbates—who is working on a polling feature that regularly checks to see if the list of ports has changed—has discovered that ALSA will crash if too many port instances are created, since node-midi doesn't provide any means for releasing the underlying RtMidi and ALSA resources it creates.

Given this reality on Linux, it seems that Flocking needs to be much lazier about when it actually allocates an underlying <code>MIDIIn</code> or <code>MIDIOut</code> instances—this should be deferred until the <code>MIDIPort</code> is actually opened.

This issue will be addressed in [the new flocking-midi library](https://github.com/fluid-studios/flocking-midi).

**Comment by simonbates** [comment]
As a work around, I have created a fork of node-midi that adds a method to the input and output objects to explicitly free the underlying RtMidi objects. I have also made some changes to Flocking to perform this explicit freeing whenever the ports are refreshed.

- node-midi changes: https://github.com/simonbates/node-midi/tree/release-rtmidi
- Flocking changes: https://github.com/simonbates/Flocking/tree/midi-release-rtmidi

See also:

- https://github.com/justinlatimer/node-midi/issues/118

**Comment by colinbdclark** [comment]
Flocking no longer directly supports Node.js, so I'm closing this issue.
