### ISSUE TITLE
Flocking's demos break when it is installed using npm 3

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/Flocking#198]
npm is probably still not fully suitable for development of web projects, but it's significantly better in a few key ways than Bower—particularly because it does not require built assets such as concatenated files to be included in the source tree.

npm 3 introduced a flattening of the <code>node_modules</code> directory hierarchy, which makes it a bit easier to use for web-based projects. However, Flocking's demos (such as the Playground) still assume the hierarchical dependency structure of npm 2.

Given this, we will need to introduce the requirement to use npm 3 when developing Flocking (this won't be an issue for users who are installing Flocking in their own projects, I don't think), so that we can update the demo paths to a flattened structure and fix this breakage for anyone who has a modern version of Node installed.

**Comment by TheAlphaNerd** [comment]
I think it is reasonable to move the demo's to expect npm v3.x and higher

By January 2017 both v0.10.x and v0.12.x of node will be end of life. That will leave the LTS version of v4.x as the only node release still shipping with v2.x of npm.

As of today the Node.js download page only offers v6.x and v7.x as download options... so new users will not likely be running on v4.x

**Comment by colinbdclark** [comment]
Thanks for the perspective, @TheAlphaNerd. I agree. Flocking's a small project with limited resources, so I think it's fair to [support the only latest Node LTS](https://github.com/colinbdclark/flocking#compatibility) for now.
