### ISSUE TITLE
Add support for automated testing on Windows using the Quality Infrastructure's Vagrant box

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/Flocking#219]
Currently, Flocking has basic support for VM-based testing of Linux using the Quality Infrastructure. However, it seems to me that it's much more important to have good tests on Windows 10, including both in Node.js and all browsers (Edge has great Web Audio support now).

This will require some custom vagrant provisioning scripts or, better yet, a switch to @amatas' [GPII continuous integration Vagrant plugin](https://github.com/amatas/vagrant-gpii-ci).

**Comment by amatas** [comment]
Hi @colinbdclark, here you have a PR with some code to address this issue, I hope it is helpful
