### ISSUE TITLE
Use aurora.js for decoding

### ISSUE THREAD

**Issue by echo66** [colinbdclark/Flocking#84]
Aurora.js (https://github.com/audiocogs/aurora.js/) is a open source project dedicated to audio file decoding and includes formats that flocking does not. And, after all, the aurora project is focused on the decoding stuff.

**Comment by colinbdclark** [comment]
Since MP3 support is now available across all major browsers (including Firefox), I'm going to close this issue. If anyone has a burning need for FLAC, ALAC, or AAC support, we can open up a more specific ticket for this feature.
