### ISSUE TITLE
Synth's instances

### ISSUE THREAD

**Issue by AlesTsurko** [colinbdclark/Flocking#94]
Can't figured out how to create a synth instance. For example, I create a synth:

```javascript
var synth = flock.synth({
   synthDef: {
      ugen: "flock.ugen.triggerGrains",
      // some parameters here
      speed: 2.0
   }
});
```

After that I want to initialize two such synth with different speed. Like if I would do in SC:
```supercollider
a = Synth("name", [\speed, 1]);
b = Synth("name", [\speed, 2]);
```
Does it possible?

**Comment by AlesTsurko** [comment]
Just found the solution in Multiple synths example. Sorry.

**Comment by colinbdclark** [comment]
No worries, I'm always happy to answer questions! I'll document the best ways to do it here, just so others can benefit.

The best way is define your own type of synth. At the moment, the syntax is a little bit verbose for this, as it is based on Infusion, the framework underneath Flocking. Here's an example:

    fluid.defaults("tsurko.grainSynth", {
        gradeNames: ["flock.synth"],
        synthDef: {
            ugen: "flock.ugen.triggerGrains",
            speed: 2.0
        }
    });

This defines your custom synth. The first argument is the synth's name. In Flocking, all synths are located inside a "namespace"--this can be whatever you want, for example your name or the name of your composition. In this case, I just used <code>tsurko</code> as the root namespace. Then, separated by a dot, you give the synth a name; here, it's <code>grainSynth</code>.

The second argument is a list of default values for your synth, including the synth. New instances of your synth can then be instantiated like this:

    var a = tsurko.grainSynth();

If you want to override the default values, as in your SuperCollider example above, you can do this:

    var b = tsurko.grainSynth({
        synthDef: {
            speed: 1.0
        }
    });

You can see some examples of how I use this approach of defining basic "grades" (types in Infusion's vocabulary) and then overrriding parameters and mixing in additional unit generators here in a composition of mine:

https://github.com/colinbdclark/compositions/blob/master/greenwich-park/js/instruments.js

I will be introducing a newer, simpler syntax for defining synth types, <code>flock.define()</code> in Flocking 0.2.0, sometime in the next few months.

An alternative is to do something super simple like:

    var grainSynthOptions = {
        synthDef: {
            id: "granulator",
            ugen: "flock.ugen.triggerGrains",
            speed: 2.0
        }
    };

    var a = flock.synth(grainSynthOptions);
    a.set("granulator.speed", 2.0);

    var b = flock.synth(grainSynthOptions);
    b.set("granulator.speed", 1.0);

I hope this helps, and makes some degree of sense. I'll try to turn this into some documentation soon.

**Comment by AlesTsurko** [comment]
Thank you for such comprehensive answer!
My solution (based on the example) was creating a function with argument, then use it as a constructor:
``` javascript
function synth(rate) {
 return flock.synth({
    synthDef: {
       ugen: "flock.ugen.triggerGrains",
       // some parameters here
       speed: rate
    }
 })
};

var newSynth = synth(2.0);
var newNewSynth = synth(0.5);
```
Or without the argument:
``` javascript
function synth() {
 return flock.synth({
    synthDef: {
       id: "granulator",
       ugen: "flock.ugen.triggerGrains",
       // some parameters here
    }
 })
};

var newSynth = synth();
newSynth.set("granulator.speed", 0.5);

var newNewSynth = synth();
newNewSynth.set("granulator.speed", 2.0);
```
