### ISSUE TITLE
Sound engine crashes when using playBuffer with negative speed

### ISSUE THREAD

**Issue by AlesTsurko** [colinbdclark/Flocking#96]
Hi Colin! I don't know is it a bug or I do something wrong. But when I try to change playBuffer to negative speed (reverse playback) the sound is crashing when playing position reaches 0.
My synth is:
```javascript
{
 id: "synth",
 ugen: "flock.ugen.playBuffer",
 buffer: {
  id: "sample",
  url: "/sample.mp3"
 },
 trigger: 0,
 loop: 1,
 speed: -1
}
```
Also it looks like with negative value playBuffer ignores start and end parameters. I use GUI element to set the start and end position, but with positive speed it's worked fine.

**Comment by colinbdclark** [comment]
Hi Ales! Yes, I can also reproduce this issue. It looks like the playBuffer unit generator doesn't currently support negative speed values. I'll try to whip something up soon to address this.

As a workaround in the meantime, is it possible that using <code>flock.ugen.readBuffer</code> and driving a <code>flock.ugen.phasor</code> backwards might do the trick?

**Comment by AlesTsurko** [comment]
Great! Thanks!
I've tried to make it with phasor in the playground through changing the increment to negative value or setting the start parameter bigger than the end, but again got crash... I just don't see any way to make the phasor backward, except of subtracting the output of the phasor from the sample length. Is it possible? And are there any other ways?

**Comment by colinbdclark** [comment]
I finally found a spare moment to add support for running <code>flock.ugen.playBuffer</code> backwards using a negative <code>speed</code> input. It's in the 0.1.x branch. If it works for you, I'll include it as part of the Flocking 0.1.1 release, along with some other buffer-related fixes.

**Comment by AlesTsurko** [comment]
It works! Thanks!
